import { Platform } from "react-native";
import { Colors } from "./Colors";


export const API_CARD_WIDTH = 813
export const API_CARD_HEIGHT = 1185
export const API_CARD_CROPPED_WIDTH = 622
export const API_CARD_CROPPED_HEIGHT = 622

export const DEFAULT_HORIZONTAL_PADDING = 10
export const CARD_FETCH_LIMIT = Platform.OS == "web" ? 120 : 60
export const DECK_FETCH_LIMIT = Platform.OS == "web" ? 120 : 60


export const AppConstants = {
    icon: {
        size: 32,
        color: Colors.orange
    },
    hitSlopLarge: {
        left: 20,
        top: 20,
        right: 20,
        bottom: 20
    },
    hitSlop: {
        left: 10,
        top: 10,
        right: 10,
        bottom: 10
    },
    CARD_FETCH_LIMIT: 42,
    DECK_FETCH_LIMIT: 32,
    USER_FETCH_LIMIT: 100,
    maxDeckDescrLenght: 5000,
    githubUrl: "https://github.com/VitorTz/battle-city",
    ygoRuleLink: "https://www.yugioh-card.com/en/downloads/rulebook/SD_RuleBook_EN_10.pdf",
    profileOptions: [
        {
          title: "Profile",
          subtitle: "name, email, password",
          iconName: "person-outline",
          shouldShowLoadingStatus: false
        },
        {
          title: "Settings",
          subtitle: "color theme",
          iconName: "settings-outline",
          shouldShowLoadingStatus: false
        },
        {
          title: "Github",
          subtitle: "source code",
          iconName: "logo-github",
          shouldShowLoadingStatus: false
        },
        {
          title: "Logout",
          subtitle: null,
          iconName: "log-out-outline",
          shouldShowLoadingStatus: true
        }
    ],
    blurhash: '|rF?hV%2WCj[ayj[a|j[az_NaeWBj@ayfRayfQfQM{M|azj[azf6fQfQfQIpWXofj[ayj[j[fQayWCoeoeaya}j[ayfQa{oLj?j[WVj[ayayj[fQoff7azayj[ayj[j[ayofayayayj[fQj[ayayj[ayfjj[j[ayjuayj['
}

export const DECK_TYPES = [
  "TCG",
  "Structure",
  "Community",
  "OCG",
  "Anime",
  "Starter",
  "Speed Duel"
]


export const ARCHETYPES = [
    "Indestructible Insect",
    "Symphonic Warrior",
    "Egyptian God",
    "Vampire",
    "Runick",
    "Raidraptor",
    "Saber",
    "Sphinx",
    "Memento",
    "Guardian",
    "Purrely",
    "Nekroz",
    "Photon",
    "Umbral Horror",
    "Resonator",
    "Cxyz",
    "Heraldic",
    "Underworld",
    "Stardust",
    "Vaylantz",
    "Circular",
    "Vassal",
    "Magikey",
    "Super Quant",
    "Aquamirror",
    "Man-Eater Bug",
    "Prank-Kids",
    "Cosmic Synchro Monster",
    "Jurrac",
    "Possessed",
    "Altergeist",
    "Fluffal",
    "Red-Eyes",
    "Genex",
    "Synchron",
    "Batteryman",
    "Anti",
    "Fishborg",
    "Regenesis",
    "Gusto",
    "Monarch",
    "Numeron",
    "Gold Pride",
    "25Th Anniversary Monsters",
    "Megalith",
    "Malefic",
    "Veda",
    "Iron Chain",
    "Rose",
    "Magician",
    "Favorite",
    "Vision Hero",
    "Evil Hero",
    "Rescue Squad",
    "Bujin",
    "Golden Castle Of Stromberg",
    "Gladiator",
    "\"C\"",
    "Ursarctic",
    "Gaia Knight",
    "World Chalice",
    "Horus The Black Flame Dragon",
    "Doriado",
    "Chemicritter",
    "Mask",
    "Masked Hero",
    "Abyss-",
    "Utopic",
    "Cloudian",
    "Azamina",
    "Rescue-Ace",
    "Battlewasp",
    "Metalmorph",
    "Scrap-Iron",
    "Advanced Crystal Beast",
    "Hi-Speedroid",
    "Celebration",
    "Crusadia",
    "Dragonmaid",
    "Fusion",
    "Golden Land",
    "Elementsaber",
    "Flower Cardian",
    "Wind-Up",
    "Fortress Whale",
    "P.U.N.K.",
    "Ninja",
    "A-To-Z",
    "Recipe",
    "Geargia",
    "Gorgonic",
    "Penguin",
    "G Golem",
    "Infernoid",
    "Rokket",
    "Snake-Eye",
    "Amazement",
    "Valkyrie",
    "Hyperion",
    "Pendulum",
    "Void",
    "Recolored Counterpart",
    "Boot-Up",
    "Kuriboh",
    "T.G.",
    "Crystal",
    "Diabell",
    "Book Of",
    "Malicevorous",
    "Magistus",
    "Kozmo",
    "Magnet Warrior",
    "Marincess",
    "Springans",
    "Armed Dragon",
    "Elemental Hero",
    "Toy",
    "Trap Monster",
    "Field Searcher",
    "Sunseed",
    "Dark World",
    "Fairy",
    "Hazy",
    "Supreme King",
    "Magician Girl",
    "Gem Dragon",
    "Predap",
    "Cipher",
    "Predaplant",
    "Prediction Princess",
    "Performapal",
    "Tindangle",
    "Virtual World",
    "Hunder",
    "Machine Angel",
    "Mannadium",
    "Black Luster Soldier",
    "Umi",
    "-Eyes Dragon",
    "Curse Of Dragon",
    "Shining Sarcophagus",
    "Majespecter",
    "Counter Fairy",
    "B.E.S.",
    "Mathmech",
    "Ghostrick",
    "Flame Swordsman",
    "Attribute Summoner",
    "War Rock",
    "Laval",
    "Impcantation",
    "Superheavy Samurai",
    "Burning Abyss",
    "Shiranui",
    "Plunder Patroll",
    "Shaddoll",
    "Melffy",
    "Dogmatika",
    "Dracoslayer",
    "Pendulum Dragon",
    "Grepher",
    "Evol",
    "Synchro",
    "Endymion",
    "D/D",
    "Kaiju",
    "Celtic Guard",
    "Galaxy",
    "Millennium",
    "Libromancer",
    "Cyber",
    "Stellarknight",
    "Jinzo",
    "Lswarm",
    "Zera",
    "Ally Of Justice",
    "Time Thief",
    "Beetrooper",
    "Evil★Twin",
    "Mayakashi",
    "Darklord",
    "Zefra",
    "Kashtira",
    "Fire King",
    "Ritual Beast",
    "Infestation",
    "Constellar",
    "Light And Darkness Dragon",
    "Nephthys",
    "Demise",
    "Simorgh",
    "Codebreaker",
    "Legendary Knight",
    "Ojama",
    "Vendread",
    "Dododo",
    "Alligator",
    "Cupid",
    "Knight",
    "Centur-Ion",
    "Gagaga",
    "Hieratic",
    "Corn",
    "Abyss Script",
    "Koala",
    "Cyber Angel",
    "Bugroth",
    "Test",
    "Attraction",
    "Spirit Message",
    "Toon",
    "S-Force",
    "D.D.",
    "Spiritual Art",
    "Dream Mirror",
    "Eldlich",
    "Machina",
    "Adamancipator",
    "Despia",
    "Heroic",
    "Power Tool",
    "Abyss Actor",
    "Transcendosaurus",
    "Dracoverlord",
    "Tri-Brigade",
    "Fairy Tail",
    "Madoor",
    "Evoltile",
    "Icejade",
    "Phantom Beast",
    "Ancient Treasure",
    "Relinquished",
    "Onomat",
    "Orcust",
    "Blackwing",
    "Graydle",
    "Blue-Eyes",
    "Risebell",
    "Blue Tears",
    "Raizeol",
    "Performage",
    "Contact",
    "Mist Valley",
    "Watt",
    "Clear Wing",
    "Archfiend",
    "Fortune Fairy",
    "Zombie Counterpart",
    "Labrynth",
    "Morganite",
    "Witchcrafter",
    "Mikanko",
    "Ashened",
    "Rainbow Bridge",
    "Dark Magician",
    "Mekk-Knight",
    "Anotherverse",
    "Doll",
    "Uniform Nomenclature",
    "Guardragon",
    "Karakuri",
    "Dragon Ruler",
    "Overlay",
    "Evil Eye",
    "Scareclaw",
    "Earthbound",
    "Destruction Sword",
    "Stealth Kragen",
    "Digital Bug",
    "Tenyi",
    "Traptrix",
    "Swordsoul",
    "Chrysalis",
    "Gimmick Puppet",
    "Cyberdark",
    "Paleozoic",
    "Ra",
    "Sangen",
    "Bonding",
    "Thunder Dragon",
    "The Sanctuary In The Sky",
    "Rank-Up-Magic",
    "Shark",
    "Skilled Magician",
    "Greed",
    "Amorphage",
    "A.I.",
    "Cynet",
    "Visas",
    "White",
    "Spider",
    "Star",
    "Phantasm",
    "Phantom Knights",
    "Fiendsmith",
    "The Agent",
    "Drytron",
    "Heraldry",
    "Frightfur",
    "Sinful Spoils",
    "Aesir",
    "Appliancer",
    "Swarm Of",
    "Martial Art Spirit",
    "Infernoble Knight",
    "Motor",
    "Goblin",
    "Dice",
    "Salamandra",
    "Crystron",
    "Flamvell",
    "Voiceless Voice",
    "Igknight",
    "Alien",
    "Serket",
    "Puppet",
    "Six Strike",
    "Dinowrestler",
    "Starry Knight",
    "Code Talker",
    "Branded",
    "Gishki",
    "Number",
    "Utopia",
    "Cyber Dragon",
    "Infernity",
    "Ogdoadic",
    "Assault Mode",
    "Naturia",
    "Skull Servant",
    "Schoolwork",
    "Metaphys",
    "Chimera",
    "K9",
    "Sylvan",
    "Subterror",
    "Spright",
    "Fan-Made Cards",
    "Argostars",
    "Gransolfachord",
    "Roland",
    "Dark Counterpart",
    "Krawler",
    "Ice Barrier",
    "Fire Formation",
    "Clear",
    "Slime",
    "Gogogo",
    "Charmer",
    "Danger!",
    "Speedroid",
    "Djinn",
    "Hole",
    "Deep Sea",
    "Panik'S Monsters",
    "Priestess",
    "Neos",
    "Six Samurai",
    "Lady Of Lament",
    "Morphtronic",
    "Venom",
    "Zexal",
    "Exodd",
    "Mirror Trap",
    "Arcana Force",
    "Lunalight",
    "Adventurer",
    "Sea Stealth",
    "Cubic",
    "Ancient Warriors",
    "Gravekeeper'S",
    "Apoqliphort",
    "Lyrilusc",
    "Materiactor",
    "Inzektor",
    "Adventurer Token",
    "Maliss",
    "Knightmare",
    "Solfachord",
    "Parasite",
    "Labyrinth Wall",
    "Divine Dragon",
    "Rikka",
    "Unchained",
    "Shinobird",
    "Butterspy",
    "Primite",
    "Ancient Fairy Dragon",
    "Neo Space",
    "Aqua Jet",
    "Infinitrack",
    "Wedju",
    "Blaze Accelerator",
    "F.A.",
    "Lightsworn",
    "Myutant",
    "Aroma",
    "Gadget",
    "Apophis",
    "Empower",
    "From The Underworld",
    "Fortune Lady",
    "Gem-",
    "Gouki",
    "Paladins Of Dragons",
    "Mythical Beast",
    "Sunavalon",
    "Destiny Hero",
    "Gladiator Beast",
    "Timelord",
    "Butterfly",
    "Wight",
    "Ryu-Ge",
    "Konami Arcade Games",
    "Gaia The Fierce Knight",
    "Mecha Phantom Beast",
    "Vanquish Soul",
    "Mystical Beast Of The Forest",
    "Superheavy",
    "Dinomist",
    "Junk",
    "Glacial Beast",
    "Odd-Eyes",
    "The Weather",
    "Mitsurugi",
    "Magical Musket",
    "Yubel",
    "Rose Dragon",
    "Trickstar",
    "Nemeses",
    "Barian'S",
    "Nemleria",
    "Holy Knight",
    "Tachyon",
    "Bystial",
    "Felgrand",
    "Diabellstar",
    "Herald",
    "Scrap",
    "Star Seraph",
    "Sunvine",
    "Mermail",
    "Neo-Spacian",
    "Yummy",
    "Psy-Frame",
    "Allure Queen",
    "Signature Move",
    "Battlin' Boxing",
    "Ancient Gear",
    "Edge Imp",
    "Artifact",
    "Exchange Of The Spirit",
    "Evolsaur",
    "Invoked",
    "Jester",
    "Deskbot",
    "Borrel",
    "Heart",
    "Gunkan",
    "Mimighoul",
    "Empowered Warrior",
    "Harpie",
    "Dinomorphia",
    "Tenpai Dragon",
    "Albaz Dragon",
    "Solemn",
    "Fire Fist",
    "Majestic",
    "Parshath",
    "Nouvelles",
    "Amazoness",
    "Lil-La",
    "Tearlaments",
    "Metalfoes",
    "X-Saber",
    "Gandora",
    "Noble Arms",
    "Chronomaly",
    "Doodle Beast",
    "Frog",
    "Dragunity",
    "Sky Striker",
    "Aether",
    "Therion",
    "Gizmek",
    "Koa'Ki Meiru",
    "Nemurelia",
    "Bamboo Sword",
    "Ki-Sikil",
    "Sacred Beast",
    "Jar",
    "Dragon Tail",
    "Volcanic",
    "Fossil",
    "Sky Scourge",
    "Forbidden",
    "White Forest",
    "Meklord",
    "Fleur",
    "Ghoti",
    "Duston",
    "Maju",
    "Phantasm Spiral",
    "Yosenju",
    "Roid",
    "Skyblaster",
    "Starliege",
    "Chaos",
    "Abc",
    "Train",
    "U.A.",
    "Seventh",
    "Gate Guardian",
    "Dark Contract",
    "Temple Of The Kings",
    "Ninjitsu Art",
    "Battlin' Boxer",
    "Doll Monster",
    "Polymerization",
    "Qli",
    "Silent Swordsman",
    "Vylon",
    "Secret Six Samurai",
    "Worm",
    "Tellarknight",
    "Fur Hire",
    "Bounzer",
    "Elemental Lord",
    "Evolzar",
    "Salamangreat",
    "Noble Knight",
    "Galaxy-Eyes",
    "Dark Scorpion",
    "Dual Avatar",
    "Live★Twin",
    "Broken World",
    "Battleguard",
    "Vernusylph",
    "Hero",
    "Mokey Mokey",
    "With Eyes Of Blue",
    "Patissciel",
    "Trap Hole",
    "Barbaros",
    "Exodia",
    "Firewall",
    "Zoodiac",
    "Draconia",
    "Aquaactress",
    "Horus",
    "Kairyu-Shin",
    "Nimble",
    "Tistina",
    "World Legacy",
    "Emblema",
    "Reptilianne",
    "@Ignister",
    "Ryzeal",
    "Generaider",
    "Mulcharmy",
    "Vaalmonica",
    "Eyes Restrict",
    "Infernoble Arms",
    "Triamid",
    "Spyral",
    "Cataclysmic",
    "Super Defense Robot",
    "Floowandereeze",
    "Spellbook",
    "Crystal Beast",
    "Exosister",
    "Chaos Phantom",
    "Doodlebook",
    "Melodious",
    "Prophecy",
    "Nordic",
    "Wicked God",
    "Steelswarm",
    "Potan",
    "Yang Zing",
    "Ragnaraika",
    "Atlantean",
    "Madolche",
    "Fabled",
    "Silent Magician",
    "Windwitch",
    "Xyz",
    "Eldlixir",
    "True Draco",
    "Live☆Twin",
].sort()

export const RACES = [
  "Yubel",
  "Chazz Princet",
  "Wyrm",
  "Continuous",
  "Christine",
  "Ritual",
  "Adrian Gecko",
  "Counter",
  "David",
  "Alexis Rhodes",
  "Seto Kaiba",
  "Field",
  "Syrus Truesda",
  "Lumis And Umb",
  "Chumley Huffi",
  "Cyberse",
  "Yami Yugi",
  "Ishizu Ishtar",
  "Machine",
  "The Supreme K",
  "Pegasus",
  "Kagemaru",
  "Normal",
  "Bastion Misaw",
  "Camula",
  "Abidos The Th",
  "Yugi",
  "Psychic",
  "Espa Roba",
  "Joey",
  "Axel Brodie",
  "Jesse Anderso",
  "Dragon",
  "Titan",
  "Dr. Vellian C",
  "Spellcaster",
  "Aqua",
  "Nightshroud",
  "Thunder",
  "Tania",
  "Illusion",
  "Keith",
  "Mako",
  "Fish",
  "Thelonious Vi",
  "Andrew",
  "Divine-Beast",
  "Fiend",
  "Mai Valentine",
  "Yami Bakura",
  "Don Zaloog",
  "Odion",
  "Reptile",
  "Equip",
  "Insect",
  "Dinosaur",
  "Bonz",
  "Warrior",
  "Plant",
  "Zombie",
  "Quick-Play",
  "Mai",
  "Winged Beast",
  "Zane Truesdal",
  "Weevil",
  "Amnael",
  "Creator God",
  "Pyro",
  "Jaden Yuki",
  "Rock",
  "Tyranno Hassl",
  "Emma",
  "Arkana",
  "Sea Serpent",
  "Beast",
  "Kaiba",
  "Paradox Broth",
  "Yami Marik",
  "Joey Wheeler",
  "Tea Gardner",
  "Aster Phoenix",
  "Beast-Warrior",
  "Lumis Umbra",
  "Ishizu",
  "Fairy",
  "Rex"
].sort()

export const CARD_TYPES = [
  "Continuous Spell",
  "Skill - Yugi",
  "Xyz Effect Monster",
  "Skill - Don Zaloog",
  "Skill - Arkana",
  "Skill - Lumis And Umb",
  "Counter Trap",
  "Skill - Abidos The Th",
  "Skill - Yami Marik",
  "Skill - Amnael",
  "Skill - Chumley Huffi",
  "Skill - Bastion Misaw",
  "Skill - Mako",
  "Skill - Rex",
  "Skill - The Supreme K",
  "Normal Spell",
  "Pendulum Tuner Effect Monster",
  "Skill - Tyranno Hassl",
  "Fusion Effect Monster",
  "Skill - Andrew",
  "Skill - Syrus Truesda",
  "Synchro Pendulum Effect Monster",
  "Skill - Zane Truesdal",
  "Skill - Weevil",
  "Tuner Normal Monster",
  "Fusion Pendulum Effect Monster",
  "Skill - Keith",
  "Skill - David",
  "Skill - Paradox Broth",
  "Skill - Ishizu Ishtar",
  "Ritual Tuner Effect Monster",
  "Link Monster",
  "Skill - Joey Wheeler",
  "Skill - Adrian Gecko",
  "Skill - Alexis Rhodes",
  "Normal Trap",
  "Flip Tuner Effect Monster",
  "Skill - Tania",
  "Skill - Bonz",
  "Token",
  "Skill - Lumis Umbra",
  "Skill - Jesse Anderso",
  "Synchro Effect Monster",
  "Skill - Axel Brodie",
  "Gemini Effect Monster",
  "Skill - Camula",
  "Skill - Espa Roba",
  "Fusion Tuner Monster",
  "Skill - Emma",
  "Skill - Chazz Princet",
  "Continuous Trap",
  "Skill - Seto Kaiba",
  "Xyz Pendulum Effect Monster",
  "Skill - Dr. Vellian C",
  "Xyz Monster",
  "Pendulum Effect Monster",
  "Link Effect Monster",
  "Field Spell",
  "Skill - Ishizu",
  "Union Effect Monster",
  "Normal Monster",
  "Pendulum Flip Effect Monster",
  "Equip Spell",
  "Skill - Nightshroud",
  "Skill - Mai Valentine",
  "Skill - Odion",
  "Spirit Effect Monster",
  "Ritual Effect Monster",
  "Ritual Monster",
  "Synchro Tuner Effect Monster",
  "Skill - Titan",
  "Skill - Aster Phoenix",
  "Skill - Kagemaru",
  "Skill - Christine",
  "Skill - Joey",
  "Skill - Kaiba",
  "Skill -",
  "Skill - Jaden Yuki",
  "Quick-Play Spell",
  "Skill - Mai",
  "Effect Monster",
  "Skill - Yubel",
  "Skill - Tea Gardner",
  "Ritual Pendulum Effect Monster",
  "Skill - Yami Bakura",
  "Synchro Monster",
  "Flip Effect Monster",
  "Skill - Yami Yugi",
  "Tuner Effect Monster",
  "Skill - Thelonious Vi",
  "Fusion Monster",
  "Pendulum Normal Monster",
  "Ritual Spell",
  "Pendulum Tuner Normal Monster",
  "Skill - Pegasus",
  "Toon Effect Monster",
  "Trap"
].sort()


export const FRAMETYPES = [
  "Spell",
  "Token",
  "Effect",
  "Normal_Pendulum",
  "Fusion",
  "Link",
  "Synchro",
  "Skill",
  "Ritual_Pendulum",
  "Trap",
  "Fusion_Pendulum",
  "Xyz",
  "Synchro_Pendulum",
  "Ritual",
  "Effect_Pendulum",
  "Xyz_Pendulum",
  "Normal"
].sort()

export const ATTRIBUTES = [
  "Divine", "Wind", "Earth", "Dark", "Water", "Light", "Fire"
].sort()

export const CARD_SORT_OPTIONS = [
  'name',
  'attack',
  'defence',
  'level'
]


export const SORT_DIRECTIONS = [
  "ASC",
  "DESC"
]


export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "North Korea",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "South Korea",
  "Republic of Moldova",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname"
]